# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000


development:
  adapter: postgresql
  database: stories_devise_development
  pool: 5
  timeout: 5000
  username: postgres
  password: admin

test:
  adapter: postgresql
  database: stories_devise_test
  pool: 5
  timeout: 5000
  username: postgres
  password: admin

production:
  adapter: postgresql
  database: stories_devise_production
  pool: 5
  timeout: 5000
  username: postgres
  password: admin
